project:
  fields:
    id:
      type: int
    type:
      type: string
    title:
      type: string
    start_date:
      type: date
    finish_date:
      type: date
    tasks:
      type: array

pattern:
  fields:
    id:
      type: int
    type:
      type: string
    title:
      type: string
    tasks:
      type: array
